name: Test
on:
  workflow_call:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-poetry
        with:
          poetry-version: "1.7.1"
      - run: poe unit

  integration:
    runs-on: ubuntu-latest
    needs: [ unit ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-poetry
        with:
          poetry-version: "1.7.1"
      - run: poe integration
